import React, { useState } from "react";
import './css/Dashboard.css';

import Notes from  './Notes';
import Textbox from "./Textbox";

export default function Dashboard(props){
    // List of notes generated by the user
    const [notes, setNotes] = useState([]);

    const addNote = (title, description) => {
        setNotes([...notes, {title: title, description, description}]);
    }

    const deleteNote = (index)=> {
        const newNotes = notes.filter(note => {
            return notes.indexOf(note) != index;
        });
        setNotes([...newNotes]);
    }

    const updateNote = (index, title, description) => {
        const newNotes = notes.map(note => {
            if(notes.indexOf(note) == index) {
                return { title: title, description: description }
            } else {
                return note;
            }
        });
        setNotes([...newNotes]);
    };
    

    return (
        <div className="Dashboard">
            <Textbox add={ addNote } />
            {/* Find key to update list everytime */}
            <Notes notes={ notes } update={ updateNote } delete={ deleteNote } />
        </div>
    )
}
